[package]
name = "sejong"
version = "0.1.0"
authors = ["Xiwen Li"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "*"