name: Update WASM

on:
  push:
    branches: [ main, funfoolsuzi-patch-1 ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - uses: actions/checkout@v2
      with:
        repository: funfoolsuzi/sejong-wasm
        path: wasm 
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.3.0
    - name: Run tests
      run: cargo test --verbose
      working-directory: $GITHUB_WORKSPACE/main
    - name: Build
      run: wasm-pack build --release --out-dir $GITHUB_WORKSPACE/wasm -- --features wasm
      working-directory: $GITHUB_WORKSPACE/main
    - uses: peter-evans/create-pull-request@v3
      with:
        token: $GITHUB_TOKEN
        path: wasm

