name: Update WASM

on:
  push:
    branches: [ main, funfoolsuzi-patch-1 ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - uses: actions/checkout@v2
      with:
        repository: funfoolsuzi/sejong-wasm
        path: wasm 
    - name: Print1
      run: |
        pwd
        ls -R
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.3.0
    - name: Print2
      run: |
        pwd
        ls -R
    - name: Run tests
      run: |
        cd $GITHUB_WORKSPACE/main
        cargo test --verbose
    - name: Build
      run: |
        cd $GITHUB_WORKSPACE/main
        wasm-pack build --release --out-dir $GITHUB_WORKSPACE/wasm -- --features wasm
    - name: Update wasm
      run: |
        cd $GITHUB_WORKSPACE/wasm
        date > generated.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push
