name: Update WASM

on:
  push:
    branches: [ main, funfoolsuzi-patch-1 ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - uses: actions/checkout@v2
      with:
        repository: funfoolsuzi/sejong-wasm
        path: wasm 
    - uses: jetli/wasm-pack-action@v0.3.0
    - name: Unit tests
      run: |
        cargo test --verbose
      working-directory: main
    - name: Build WASM
      run: |
        wasm-pack build --release --out-dir $GITHUB_WORKSPACE/wasm -- --features wasm
      working-directory: main
    - name: Tidy generated files
      run: |
        rm .gitignore
        date > generated.txt
        python $GITHUB_WORKSPACE/main/.github/scripts/update_package_json.py package.json
      working-directory: wasm
    - uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.SEJONG_WASM }}
        path: wasm

