name: Update WASM

on:
  push:
    branches: [ main, funfoolsuzi-patch-1 ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - uses: actions/checkout@v2
      with:
        repository: funfoolsuzi/sejong-wasm
        path: wasm 
    - uses: jetli/wasm-pack-action@v0.3.0
    - run: |
      git remote get-url origin
      cargo test --verbose
      working-directory: main
    - run: wasm-pack build --release --out-dir $GITHUB_WORKSPACE/wasm -- --features wasm
      working-directory: main
    - run: |
        rm .gitignore
        date > generated.txt
        git status
        git remote get-url origin
        git remote set-url origin https://funfoolsuzi:$GITHUB_TOKEN@github.com/funfoolsuzi/sejong-wasm.git
      working-directory: wasm
    - uses: peter-evans/create-pull-request@v3
      with:
        token: $GITHUB_TOKEN
        path: wasm

